api:
    color: 6f42c1
    description: Issues related to the GitHub API
bug:
    color: d73a4a
    description: Something isn't working as expected
enhancement:
    color: 0dd8ac
    description: New feature or improvement request
    
documentation:
    color: 007bc7
    description: Issues related to documentation
help-wanted:
    color: 7057ff
    description: Contribution opportunities available
question:
    color: ffb000
    description: Questions or need for further clarification
invalid:
    color: e4e669
    description: Issue is no longer valid or applicable
duplicate:
    color: cfd3d7
    description: Issue already reported or duplicated
wontfix:
    color: a2eeef
    description: Issue won't be fixed or addressed
feature-request:
    color: 61dafb
    description: Request for a new feature or enhancement
critical:
    color: e00808
    description: Critical issue that requires immediate attention
high-priority:
    color: ff7b72
    description: Issue with high priority
low-priority:
    color: 8c8c8c
    description: Issue with low priority
in-progress:
    color: 2a8b9d
    description: Issue currently being worked on
resolved:
    color: 28a745
    description: Issue has been resolved
feedback:
    color: d4c5f9
    description: Feedback or suggestions for improvement
testing:
    color: 36bcef
    description: Issues related to testing or test cases
hacktoberfest:
    color: ff6b00
    description: Issues related to the Hacktoberfest event
