name: Upload labels

on:
  push:
    branches:
      - main

jobs:
  upload-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shanduur/declarative-labels-sync-action@main
        with:
          owner: shanduur
          repository: ${{ github.event.repository.name }}
          token: ${{ secrets.PAT }}
