name: Upload labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml

permissions: write-all

env:
  OWNER: shanduur
  REPO: ${{ github.event.repository.name }}

jobs:
  upload-labels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - run: go install github.com/shanduur/labeler/cmd/labeler@main
    - run: labeler upload --owner ${{ env.OWNER }} --repo ${{ env.REPO }} ./.github/labels.yaml
      env:
        LABELER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
